# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metabase < Formula
  desc "CLI for Metabase — query cards, dashboards, and collections from the command line."
  homepage "https://github.com/danielbrodie/metabase-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielbrodie/metabase-cli/releases/download/v0.1.1/metabase-cli_darwin_amd64.tar.gz"
      sha256 "09af6e0a875ae731dd5b7b176d70e75e32be3b188309d2cf2bbc37a069b35e9d"

      define_method(:install) do
        bin.install "metabase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielbrodie/metabase-cli/releases/download/v0.1.1/metabase-cli_darwin_arm64.tar.gz"
      sha256 "c57d685acb12221ded4611608aabee675fbeece2d69ca508d26885aa5613dae0"

      define_method(:install) do
        bin.install "metabase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielbrodie/metabase-cli/releases/download/v0.1.1/metabase-cli_linux_amd64.tar.gz"
      sha256 "edcac9054af35b2f6efe3f60471ac7b2b18e9419ee43b7588a7889e9f8349633"
      define_method(:install) do
        bin.install "metabase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielbrodie/metabase-cli/releases/download/v0.1.1/metabase-cli_linux_arm64.tar.gz"
      sha256 "1551428be563905850dd50123eba6070eec12983d6c40ac47bffd3ec086d822a"
      define_method(:install) do
        bin.install "metabase"
      end
    end
  end

  test do
    system "#{bin}/metabase", "--help"
  end
end
